version: '3'
services:

  collegeoflore:
    image: python:3.9
    command:
      [
        "sh",
        "-c",
        "pip install -r requirements_dev.txt -e . && adev runserver ./backend/ -p 8080"
      ]
    volumes:
      - ./:/src/
    working_dir: /src/
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.6
    user: ${UID}
    container_name: mongo
    ports:
      - "27017:27017"
    # command: --replSet rs0
    hostname: mongo
    volumes:
      - ./data/mongo:/data/db
    #  - "./replica_init.sh:/docker-entrypoint-initdb.d/replica_init.sh"

    # networks:
    #   default:
    #     external: true
    #     name: host
